using System;
using System.Collections.Generic;
using System.Text;

namespace HardwareRetroAchievements.Core
{
    public enum ConsoleID
    {
        MegaDrive = 1,
        Nintendo64,
        SuperNintendo,
        Gameboy,
        GameboyAdvance,
        GameboyColor,
        Nintendo,
        PCEngine,
        SegaCD,
        Sega32x,
        MasterSystem,
        Playstation,
        AtariLynx,
        NeoGeoPocket,
        GameGear,
        GameCube,
        AtariJaguar,
        NintendoDS,
        Wii,
        WiiU,
        Playstation2,
        Xbox,
        Skynet,
        PokemonMini,
        Atari2600,
        MSDos,
        Arcade,
        VirtualBoy,
        MSX,
        Commodore64,
        ZX81,
        Oric,
        SG1000,
        VIC20,
        Amiga,
        AtariST,
        Amstrad,
        AppleII,
        Saturn,
        Dreamcast,
        PSP,
        CDi,
        Console3D0,
        ColecoVision,
        Intellivision,
        Vectrex,
        PC8800,
        PC9800,
        PCFX,
        Atari5200,
        Atari7800,
        X86k,
        Wonderswan,
        CassetteVision,
        SuperCassetteVision
    }
}
